apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: monorepo-component1
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    mintmaker.appstudio.redhat.com/disabled: 'true'
spec:
  application: monorepo-app
  componentName: monorepo-component1
  source:
    git:
      url: https://github.com/mmorhun/test-components.git
      revision: monorepo
      context: ./component1dir
      dockerfileUrl: Dockerfile
